---
title: "Agenda"
---


# Slides
All slides are available at
<https://github.com/sr320/course-ASI-2024/tree/main/slides>

# Notepads

[google docs notepad](https://docs.google.com/document/d/1hEh-KW_sLq0EjMR5IuQjB8H629X2exJZbFefLs6upqE/edit?usp=sharing)






# Grading
This course will be graded. There will quizzes worth 15 pts and on the final day you will give a presentation worth 25 pts. Quizzes will be in the form of Google Forms. 

- [Quiz 1](https://forms.gle/tkFgrNQ2Qw8HEEhT8) Due 14 Jan


## Presentation 
For the presentation students will select two papers on a



# Students

| No. | Name            | Last Name | Email                        | Title/Position                                         |
|-----|-----------------|-----------|------------------------------|--------------------------------------------------------|
| 1   | Juan Francisco  | Araya     | jfaraya@u.uchile.cl          | PhD (c) in Systematics and Biodiversity                |
| 2   | Sindy           | Díaz      | sidiaz2023@udec.cl           | PhD Student MaReA                                      |
| 3   | Krystel         | Susaya    | ksusaya2023@udec.cl          | MSc Student in Oceanography                            |
| 4   | Constanza       | Saez      | constanzajasaez@udec.cl      | MSc en Preventive Veterinary Medicine. Research assistant at INCAR |
| 5   | Pablo           | Oyarzo    | POYARZO2020@udec.cl          |                                                        |
| 6   | Antonio         | Casuso    | acasuso@udec.cl              | Ph.D. in Cs. mention in Management of Renewable Aquatic Resources (MaReA). |
| 7   | Jurleys         | Vellojin  | jurleys.vellojin@ifop.cl     | PhD in Aquaculture Sciences, Researcher, IFOP          |
| 8   | Ailén           | Poza      | pozaailen@inibibb-conicet.gob.ar | PhD in Biology. Postdoc Centro I-Mar, Universidad de Los Lagos |
| 9   | Diego           | Hernández | diego.jhc@gmail.com          | MSc in Oceanography PUCV                               |
| 10  | María Fernanda  | Jiménez   | mariafernanda.jimenez@ifop.cl | PhD in Aquaculture, Researcher, IFOP                   |
| 11  | Daniela         | Díaz      | ddiazibarrola@gmail.com      | PhD Student in Aquaculture Sciences                    |
| 12  | Ana Verónica    | García    | anaverona.garciacondo@gmail.com | Aquaculture Engineer, Researcher INOCAR               |
| 13  | Natalie         | Bravo     | nbravos@unprg.edu.pe         | Biologist                                              |




# Plan

## Biology

Objective: Have general understanding of sub-organismal biology, computational framework of class. Gene expression.

-   [Course Description](/index.qmd)

-   Instructor Background

-   Class Background and Interests

-   Homeostasis

-   Cell and Molecular Biology

-   Discussion of Reproducible & Open Science

-   Overview of Framework of for Computational Component
  Need to get GitHub User names 

-   Demonstration: Bash

-   Case Study: Gene Expression
George, M. N., Cattau, O., Middleton, M. A., Lawson, D., Vadopalas, B., Gavery, M. R., … & Roberts, S. B. (2023). Triploid pacific oysters exhibit stress response dysregulation and elevated mortality following marine heatwaves.. https://doi.org/10.1101/2023.03.02.530828

[PDF](https://gannet.fish.washington.edu/seashell/snaps/Global_Change_Biology_-_2023_-_George_-_Triploid_Pacific_oysters_exhibit_stress_response_dysregulation_and_elevated.pdf)





## Epigenetics 

Objective: Understand what epigenetics is what




## Epigenetic Applications





## Evaluation Science @ INCAR


- computer work - publishing

## Presentations



# Additional Useful Resources





