project:
  type: website
  output-dir: docs

website:
  title: "Epigenetic Phenomena Connecting Climate Change and Coastal Marine Species"
  repo-url: https://github.com/sr320/course-ASI-2024
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
     
    tools:
      - icon: github
        href: https://github.com/sr320/course-ASI-2024
      

  sidebar:
    style: "docked"
    contents:
      - section: "Logistics"
        contents:
          - modules/day01.qmd

      - section: "Computation Basics"
        contents:
          - modules/00-markdown.qmd
          - modules/01-github.qmd
          - modules/02-bash.qmd
          - modules/03-rstudio.qmd
          
      - section: "Biology and Ecology"
        contents:
          - modules/slidedecks.qmd
          - modules/10-climate.qmd
          - modules/20-supp.qmd
          - modules/21-supp.qmd
          - modules/22-supp.qmd
 
      - section: "Tutorials"
        contents:
          - modules/DRAFT_DNA_methylation.qmd 

      - section: "Computer Labs"
        contents:
          - assignments/00-bash.qmd 
          - assignments/01-blast.qmd
          - assignments/02-DGE.qmd
          - assignments/06-rnaseq-snp.qmd
          - assignments/07-CG.qmd
          - assignments/08-bedtools.qmd
    
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual

